# Generated by Django 3.0.7 on 2021-12-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_pieces',
            field=models.IntegerField(default=3),
        ),
    ]
