# Generated by Django 3.0.7 on 2021-12-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_no_of_pieces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='generic',
        ),
    ]
