# Generated by Django 3.0.7 on 2022-02-05 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsewaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('paid_amount', models.IntegerField()),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esewa_user', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esewa_order', to='order.Order')),
            ],
            options={
                'ordering': ['-paid_on'],
            },
        ),
    ]
