# Generated by Django 3.0.7 on 2022-02-05 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('payment_through', models.CharField(choices=[('0', 'Esewa'), ('1', 'Cash On Delivery')], default=0, max_length=50)),
                ('total_amount', models.PositiveIntegerField()),
                ('delivery_charge', models.PositiveIntegerField()),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ordered_on'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('available_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_created_by', to=settings.AUTH_USER_MODEL)),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_product', to='product.Product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('related_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems_order', to='order.Order')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems_product', to='product.Product')),
            ],
        ),
    ]
